### ISSUE TITLE
Publish to gradle plugins repo

### ISSUE THREAD

**Issue by borice** [sebersole/gradle-maven-publish-auth#18]
Would be nice to have this plugin uploaded [here](https://plugins.gradle.org/docs/submit)
Thanks for your hard work!

**Comment by sebersole** [comment]
Thanks, I will look into that.  I am current very heads down on Hibernate 6 development but will get back to tasks like this project after.

**Comment by dedekj** [comment]
I made the deployment of this plugin to 
https://plugins.gradle.org/plugin/org.datlowe.maven-publish-auth
See the details here: https://github.com/datlowe/gradle-maven-publish-auth

@sebersole I hope this my action is not harming you or your great work in any direction. I really like this plugin. Thank you very much for it.  If you feel like any changes in my published version should be made or some "copyright info" should be stressed somewhere, just let me know. You can also pull my version and publish it easily under your own coordinates... I'm open to any suggestion.

**Comment by sebersole** [comment]
Hey Jan

I guess it depends if you want to take over ownership of that plugin.

**Comment by dedekj** [comment]
Well Steve, 
I'm not that much interested in maintaining / taking over ownership of the plugin. I don't have much free time to give. And I'm also not much experienced in the development of gradle plugins.

I just wanted to be able to use the plugin in a simple way, with the new "downloading auth feature", which is not part of the maven central version ('org.hibernate.build.gradle:gradle-maven-publish-auth:jar:2.0.1'
). 

I'm very happy that it was not difficult to make the publication and I want to be sure that this action is ok for you...

I used our company (org.datlowe) prefix, because the published version was slightly modified by myself, but if you wold like it having a different prefix, I will rename it...

**Comment by sebersole** [comment]
I just did a release of this that publishes the plugin to the Gradle portal now, amongst many other improvements - https://plugins.gradle.org/plugin/org.hibernate.build.maven-repo-auth/3.0.0
